var namespace_x_h =
[
    [ "ArrayFileEdit", "class_x_h_1_1_array_file_edit.html", "class_x_h_1_1_array_file_edit" ],
    [ "Backup", "class_x_h_1_1_backup.html", "class_x_h_1_1_backup" ],
    [ "ChangePassword", "class_x_h_1_1_change_password.html", "class_x_h_1_1_change_password" ],
    [ "ClassicPluginMenu", "class_x_h_1_1_classic_plugin_menu.html", "class_x_h_1_1_classic_plugin_menu" ],
    [ "Controller", "class_x_h_1_1_controller.html", "class_x_h_1_1_controller" ],
    [ "CoreArrayFileEdit", "class_x_h_1_1_core_array_file_edit.html", "class_x_h_1_1_core_array_file_edit" ],
    [ "CoreConfigFileEdit", "class_x_h_1_1_core_config_file_edit.html", "class_x_h_1_1_core_config_file_edit" ],
    [ "CoreLangFileEdit", "class_x_h_1_1_core_lang_file_edit.html", "class_x_h_1_1_core_lang_file_edit" ],
    [ "CoreTextFileEdit", "class_x_h_1_1_core_text_file_edit.html", "class_x_h_1_1_core_text_file_edit" ],
    [ "CSRFProtection", "class_x_h_1_1_c_s_r_f_protection.html", "class_x_h_1_1_c_s_r_f_protection" ],
    [ "FileEdit", "class_x_h_1_1_file_edit.html", "class_x_h_1_1_file_edit" ],
    [ "IntegratedPluginMenu", "class_x_h_1_1_integrated_plugin_menu.html", "class_x_h_1_1_integrated_plugin_menu" ],
    [ "Li", "class_x_h_1_1_li.html", "class_x_h_1_1_li" ],
    [ "Link", "class_x_h_1_1_link.html", "class_x_h_1_1_link" ],
    [ "LinkChecker", "class_x_h_1_1_link_checker.html", "class_x_h_1_1_link_checker" ],
    [ "Mail", "class_x_h_1_1_mail.html", "class_x_h_1_1_mail" ],
    [ "Mailform", "class_x_h_1_1_mailform.html", "class_x_h_1_1_mailform" ],
    [ "PageDataEditor", "class_x_h_1_1_page_data_editor.html", "class_x_h_1_1_page_data_editor" ],
    [ "PageDataModel", "class_x_h_1_1_page_data_model.html", "class_x_h_1_1_page_data_model" ],
    [ "PageDataRouter", "class_x_h_1_1_page_data_router.html", "class_x_h_1_1_page_data_router" ],
    [ "PageDataView", "class_x_h_1_1_page_data_view.html", "class_x_h_1_1_page_data_view" ],
    [ "Pages", "class_x_h_1_1_pages.html", "class_x_h_1_1_pages" ],
    [ "PasswordForgotten", "class_x_h_1_1_password_forgotten.html", "class_x_h_1_1_password_forgotten" ],
    [ "PluginArrayFileEdit", "class_x_h_1_1_plugin_array_file_edit.html", "class_x_h_1_1_plugin_array_file_edit" ],
    [ "PluginConfig", "class_x_h_1_1_plugin_config.html", "class_x_h_1_1_plugin_config" ],
    [ "PluginConfigFileEdit", "class_x_h_1_1_plugin_config_file_edit.html", "class_x_h_1_1_plugin_config_file_edit" ],
    [ "PluginLanguageFileEdit", "class_x_h_1_1_plugin_language_file_edit.html", "class_x_h_1_1_plugin_language_file_edit" ],
    [ "PluginMenu", "class_x_h_1_1_plugin_menu.html", "class_x_h_1_1_plugin_menu" ],
    [ "PluginTextFileEdit", "class_x_h_1_1_plugin_text_file_edit.html", "class_x_h_1_1_plugin_text_file_edit" ],
    [ "Publisher", "class_x_h_1_1_publisher.html", "class_x_h_1_1_publisher" ],
    [ "Search", "class_x_h_1_1_search.html", "class_x_h_1_1_search" ],
    [ "TextFileEdit", "class_x_h_1_1_text_file_edit.html", "class_x_h_1_1_text_file_edit" ]
];